/**
 * Returns an array with count items generated by callback
 * @param count
 * @param callback
 * @returns {Array}
 */
export default function repeat(count, callback) {
  const results = [];
  for (let i = 0; i < count; i++) {
    results.push(callback(i));
  }
  return results;
}
